name: Build and Release CSV to ASC Converter

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pandas tkinter
        
    - name: Verify files exist
      run: |
        if (!(Test-Path "csv_to_asc.py")) {
          Write-Error "csv_to_asc.py file does not exist!"
          exit 1
        }
        Write-Host "✓ csv_to_asc.py found"
        
    - name: Clean old build files
      run: |
        if (Test-Path "dist") { Remove-Item -Recurse -Force "dist" }
        if (Test-Path "build") { Remove-Item -Recurse -Force "build" }
        if (Test-Path "*.spec") { Remove-Item -Force "*.spec" }
        Write-Host "✓ Cleaned old build files"
        
    - name: Build executable
      run: |
        python -m PyInstaller --onefile --windowed --icon=icon.ico --name "CSV_to_ASC" csv_to_asc.py
        
    - name: Verify executable
      run: |
        if (!(Test-Path "dist\CSV_to_ASC.exe")) {
          Write-Error "Executable was not created!"
          exit 1
        }
        $fileSize = (Get-Item "dist\CSV_to_ASC.exe").Length
        Write-Host "✓ Executable created successfully: $fileSize bytes"
        
    - name: Clean temporary files
      run: |
        if (Test-Path "build") { Remove-Item -Recurse -Force "build" }
        if (Test-Path "__pycache__") { Remove-Item -Recurse -Force "__pycache__" }
        Write-Host "✓ Cleaned temporary files"
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/CSV_to_ASC.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}